class: de.unihamburg.sickstore.database.SickServer
port: 54000
queryHandler:
    class: de.unihamburg.sickstore.backend.QueryHandler
    anomalyGenerator:
        class: de.unihamburg.sickstore.backend.anomaly.BasicAnomalyGenerator
#        stalenessGenerator:
#            class: de.unihamburg.sickstore.backend.anomaly.staleness.ConstantStaleness
#            foreignReads: 500
#            ownReads: 0
#        clientDelayGenerator:
#            class: de.unihamburg.sickstore.backend.anomaly.MongoDbAnomalies
        combinedGenerator:
            class: de.unihamburg.sickstore.backend.anomaly.MongoDbAnomalies
            defaultDelay: 100
            journalCommitInterval: 300
            customDelays:
                # to, from, delay
                - [primary, secondary1, 50]
                - [primary, secondary2, 20]
                - [secondary1, primary, 60]
                - [secondary2, primary, 20]
            tagSets:
                foobar:
                    A: 1
                    B: 2
    nodes:
        -
            class: de.unihamburg.sickstore.database.Node
            name: primary
            primary: true
            clientLatency: 2
            throughput:
                max: 10000.0
            tags:
                - A
                - B
        -
            class: de.unihamburg.sickstore.database.Node
            name: secondary1
            clientLatency: 1
            tags:
                - A
        -
            class: de.unihamburg.sickstore.database.Node
            name: secondary2
            clientLatency: 3
            maxThroughput: 200.0
            tags:
                - B