#!/bin/sh
HOSTS=ycsb-node1,ycsb-node2,ycsb-node3,ycsb-node4

DEFAULT_PORT=8091
CLUSTER_RAMSIZE=13000

USER_NAME=ycsb
USER_PASSWORD=Kl1b0xAxQ
BUCKET_NAME=default
BUCKET_TYPE=couchbase
BUCKET_RAMSIZE=${CLUSTER_RAMSIZE}
BUCKET_REPLICAS=1
