// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package queryMessage;

public final class Message {
    private Message() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface QueryOrBuilder extends
            // @@protoc_insertion_point(interface_extends:queryMessage.Query)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated string values = 1;</code>
         * 
         * @return A list containing the values.
         */
        java.util.List<java.lang.String> getValuesList();

        /**
         * <code>repeated string values = 1;</code>
         * 
         * @return The count of values.
         */
        int getValuesCount();

        /**
         * <code>repeated string values = 1;</code>
         * 
         * @param index The index of the element to return.
         * @return The values at the given index.
         */
        java.lang.String getValues(int index);

        /**
         * <code>repeated string values = 1;</code>
         * 
         * @param index The index of the value to return.
         * @return The bytes of the values at the given index.
         */
        com.google.protobuf.ByteString getValuesBytes(int index);
    }

    /**
     * Protobuf type {@code queryMessage.Query}
     */
    public static final class Query extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:queryMessage.Query)
            QueryOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Query.newBuilder() to construct.
        private Query(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Query() {
            values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({ "unused" })
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Query();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return queryMessage.Message.internal_static_queryMessage_Query_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return queryMessage.Message.internal_static_queryMessage_Query_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            queryMessage.Message.Query.class, queryMessage.Message.Query.Builder.class);
        }

        public static final int VALUES_FIELD_NUMBER = 1;
        private com.google.protobuf.LazyStringList values_;

        /**
         * <code>repeated string values = 1;</code>
         * 
         * @return A list containing the values.
         */
        public com.google.protobuf.ProtocolStringList getValuesList() {
            return values_;
        }

        /**
         * <code>repeated string values = 1;</code>
         * 
         * @return The count of values.
         */
        public int getValuesCount() {
            return values_.size();
        }

        /**
         * <code>repeated string values = 1;</code>
         * 
         * @param index The index of the element to return.
         * @return The values at the given index.
         */
        public java.lang.String getValues(int index) {
            return values_.get(index);
        }

        /**
         * <code>repeated string values = 1;</code>
         * 
         * @param index The index of the value to return.
         * @return The bytes of the values at the given index.
         */
        public com.google.protobuf.ByteString getValuesBytes(int index) {
            return values_.getByteString(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < values_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, values_.getRaw(i));
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < values_.size(); i++) {
                    dataSize += computeStringSizeNoTag(values_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getValuesList().size();
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof queryMessage.Message.Query)) {
                return super.equals(obj);
            }
            queryMessage.Message.Query other = (queryMessage.Message.Query) obj;

            if (!getValuesList()
                    .equals(other.getValuesList()))
                return false;
            if (!getUnknownFields().equals(other.getUnknownFields()))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getValuesCount() > 0) {
                hash = (37 * hash) + VALUES_FIELD_NUMBER;
                hash = (53 * hash) + getValuesList().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static queryMessage.Message.Query parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static queryMessage.Message.Query parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static queryMessage.Message.Query parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static queryMessage.Message.Query parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static queryMessage.Message.Query parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static queryMessage.Message.Query parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static queryMessage.Message.Query parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static queryMessage.Message.Query parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static queryMessage.Message.Query parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static queryMessage.Message.Query parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static queryMessage.Message.Query parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static queryMessage.Message.Query parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(queryMessage.Message.Query prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder()
                    : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code queryMessage.Query}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:queryMessage.Query)
                queryMessage.Message.QueryOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return queryMessage.Message.internal_static_queryMessage_Query_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return queryMessage.Message.internal_static_queryMessage_Query_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                queryMessage.Message.Query.class, queryMessage.Message.Query.Builder.class);
            }

            // Construct using queryMessage.Message.Query.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return queryMessage.Message.internal_static_queryMessage_Query_descriptor;
            }

            @java.lang.Override
            public queryMessage.Message.Query getDefaultInstanceForType() {
                return queryMessage.Message.Query.getDefaultInstance();
            }

            @java.lang.Override
            public queryMessage.Message.Query build() {
                queryMessage.Message.Query result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public queryMessage.Message.Query buildPartial() {
                queryMessage.Message.Query result = new queryMessage.Message.Query(this);
                int from_bitField0_ = bitField0_;
                if (((bitField0_ & 0x00000001) != 0)) {
                    values_ = values_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.values_ = values_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof queryMessage.Message.Query) {
                    return mergeFrom((queryMessage.Message.Query) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(queryMessage.Message.Query other) {
                if (other == queryMessage.Message.Query.getDefaultInstance())
                    return this;
                if (!other.values_.isEmpty()) {
                    if (values_.isEmpty()) {
                        values_ = other.values_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureValuesIsMutable();
                        values_.addAll(other.values_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                java.lang.String s = input.readStringRequireUtf8();
                                ensureValuesIsMutable();
                                values_.add(s);
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            private void ensureValuesIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    values_ = new com.google.protobuf.LazyStringArrayList(values_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated string values = 1;</code>
             * 
             * @return A list containing the values.
             */
            public com.google.protobuf.ProtocolStringList getValuesList() {
                return values_.getUnmodifiableView();
            }

            /**
             * <code>repeated string values = 1;</code>
             * 
             * @return The count of values.
             */
            public int getValuesCount() {
                return values_.size();
            }

            /**
             * <code>repeated string values = 1;</code>
             * 
             * @param index The index of the element to return.
             * @return The values at the given index.
             */
            public java.lang.String getValues(int index) {
                return values_.get(index);
            }

            /**
             * <code>repeated string values = 1;</code>
             * 
             * @param index The index of the value to return.
             * @return The bytes of the values at the given index.
             */
            public com.google.protobuf.ByteString getValuesBytes(int index) {
                return values_.getByteString(index);
            }

            /**
             * <code>repeated string values = 1;</code>
             * 
             * @param index The index to set the value at.
             * @param value The values to set.
             * @return This builder for chaining.
             */
            public Builder setValues(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureValuesIsMutable();
                values_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string values = 1;</code>
             * 
             * @param value The values to add.
             * @return This builder for chaining.
             */
            public Builder addValues(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureValuesIsMutable();
                values_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string values = 1;</code>
             * 
             * @param values The values to add.
             * @return This builder for chaining.
             */
            public Builder addAllValues(
                    java.lang.Iterable<java.lang.String> values) {
                ensureValuesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, values_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string values = 1;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearValues() {
                values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string values = 1;</code>
             * 
             * @param value The bytes of the values to add.
             * @return This builder for chaining.
             */
            public Builder addValuesBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureValuesIsMutable();
                values_.add(value);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:queryMessage.Query)
        }

        // @@protoc_insertion_point(class_scope:queryMessage.Query)
        private static final queryMessage.Message.Query DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new queryMessage.Message.Query();
        }

        public static queryMessage.Message.Query getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Query> PARSER = new com.google.protobuf.AbstractParser<Query>() {
            @java.lang.Override
            public Query parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Query> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Query> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public queryMessage.Message.Query getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_queryMessage_Query_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_queryMessage_Query_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\rmessage.proto\022\014queryMessage\"\027\n\005Query\022\016" +
                        "\n\006values\030\001 \003(\tb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_queryMessage_Query_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_queryMessage_Query_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_queryMessage_Query_descriptor,
                new java.lang.String[] { "Values", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}