// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package responseMessage;

public final class ResponseOuterClass {
    private ResponseOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:responseMessage.Response)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated string result = 1;</code>
         * 
         * @return A list containing the result.
         */
        java.util.List<java.lang.String> getResultList();

        /**
         * <code>repeated string result = 1;</code>
         * 
         * @return The count of result.
         */
        int getResultCount();

        /**
         * <code>repeated string result = 1;</code>
         * 
         * @param index The index of the element to return.
         * @return The result at the given index.
         */
        java.lang.String getResult(int index);

        /**
         * <code>repeated string result = 1;</code>
         * 
         * @param index The index of the value to return.
         * @return The bytes of the result at the given index.
         */
        com.google.protobuf.ByteString getResultBytes(int index);
    }

    /**
     * Protobuf type {@code responseMessage.Response}
     */
    public static final class Response extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:responseMessage.Response)
            ResponseOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Response.newBuilder() to construct.
        private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Response() {
            result_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({ "unused" })
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Response();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return responseMessage.ResponseOuterClass.internal_static_responseMessage_Response_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return responseMessage.ResponseOuterClass.internal_static_responseMessage_Response_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            responseMessage.ResponseOuterClass.Response.class,
                            responseMessage.ResponseOuterClass.Response.Builder.class);
        }

        public static final int RESULT_FIELD_NUMBER = 1;
        private com.google.protobuf.LazyStringList result_;

        /**
         * <code>repeated string result = 1;</code>
         * 
         * @return A list containing the result.
         */
        public com.google.protobuf.ProtocolStringList getResultList() {
            return result_;
        }

        /**
         * <code>repeated string result = 1;</code>
         * 
         * @return The count of result.
         */
        public int getResultCount() {
            return result_.size();
        }

        /**
         * <code>repeated string result = 1;</code>
         * 
         * @param index The index of the element to return.
         * @return The result at the given index.
         */
        public java.lang.String getResult(int index) {
            return result_.get(index);
        }

        /**
         * <code>repeated string result = 1;</code>
         * 
         * @param index The index of the value to return.
         * @return The bytes of the result at the given index.
         */
        public com.google.protobuf.ByteString getResultBytes(int index) {
            return result_.getByteString(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < result_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_.getRaw(i));
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < result_.size(); i++) {
                    dataSize += computeStringSizeNoTag(result_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getResultList().size();
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof responseMessage.ResponseOuterClass.Response)) {
                return super.equals(obj);
            }
            responseMessage.ResponseOuterClass.Response other = (responseMessage.ResponseOuterClass.Response) obj;

            if (!getResultList()
                    .equals(other.getResultList()))
                return false;
            if (!getUnknownFields().equals(other.getUnknownFields()))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getResultCount() > 0) {
                hash = (37 * hash) + RESULT_FIELD_NUMBER;
                hash = (53 * hash) + getResultList().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static responseMessage.ResponseOuterClass.Response parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static responseMessage.ResponseOuterClass.Response parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static responseMessage.ResponseOuterClass.Response parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static responseMessage.ResponseOuterClass.Response parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static responseMessage.ResponseOuterClass.Response parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static responseMessage.ResponseOuterClass.Response parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static responseMessage.ResponseOuterClass.Response parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static responseMessage.ResponseOuterClass.Response parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static responseMessage.ResponseOuterClass.Response parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static responseMessage.ResponseOuterClass.Response parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static responseMessage.ResponseOuterClass.Response parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static responseMessage.ResponseOuterClass.Response parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(responseMessage.ResponseOuterClass.Response prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder()
                    : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code responseMessage.Response}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:responseMessage.Response)
                responseMessage.ResponseOuterClass.ResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return responseMessage.ResponseOuterClass.internal_static_responseMessage_Response_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return responseMessage.ResponseOuterClass.internal_static_responseMessage_Response_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                responseMessage.ResponseOuterClass.Response.class,
                                responseMessage.ResponseOuterClass.Response.Builder.class);
            }

            // Construct using responseMessage.ResponseOuterClass.Response.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                result_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return responseMessage.ResponseOuterClass.internal_static_responseMessage_Response_descriptor;
            }

            @java.lang.Override
            public responseMessage.ResponseOuterClass.Response getDefaultInstanceForType() {
                return responseMessage.ResponseOuterClass.Response.getDefaultInstance();
            }

            @java.lang.Override
            public responseMessage.ResponseOuterClass.Response build() {
                responseMessage.ResponseOuterClass.Response result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public responseMessage.ResponseOuterClass.Response buildPartial() {
                responseMessage.ResponseOuterClass.Response result = new responseMessage.ResponseOuterClass.Response(
                        this);
                int from_bitField0_ = bitField0_;
                if (((bitField0_ & 0x00000001) != 0)) {
                    result_ = result_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.result_ = result_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof responseMessage.ResponseOuterClass.Response) {
                    return mergeFrom((responseMessage.ResponseOuterClass.Response) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(responseMessage.ResponseOuterClass.Response other) {
                if (other == responseMessage.ResponseOuterClass.Response.getDefaultInstance())
                    return this;
                if (!other.result_.isEmpty()) {
                    if (result_.isEmpty()) {
                        result_ = other.result_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureResultIsMutable();
                        result_.addAll(other.result_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                java.lang.String s = input.readStringRequireUtf8();
                                ensureResultIsMutable();
                                result_.add(s);
                                break;
                            } // case 10
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.LazyStringList result_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            private void ensureResultIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    result_ = new com.google.protobuf.LazyStringArrayList(result_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated string result = 1;</code>
             * 
             * @return A list containing the result.
             */
            public com.google.protobuf.ProtocolStringList getResultList() {
                return result_.getUnmodifiableView();
            }

            /**
             * <code>repeated string result = 1;</code>
             * 
             * @return The count of result.
             */
            public int getResultCount() {
                return result_.size();
            }

            /**
             * <code>repeated string result = 1;</code>
             * 
             * @param index The index of the element to return.
             * @return The result at the given index.
             */
            public java.lang.String getResult(int index) {
                return result_.get(index);
            }

            /**
             * <code>repeated string result = 1;</code>
             * 
             * @param index The index of the value to return.
             * @return The bytes of the result at the given index.
             */
            public com.google.protobuf.ByteString getResultBytes(int index) {
                return result_.getByteString(index);
            }

            /**
             * <code>repeated string result = 1;</code>
             * 
             * @param index The index to set the value at.
             * @param value The result to set.
             * @return This builder for chaining.
             */
            public Builder setResult(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureResultIsMutable();
                result_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string result = 1;</code>
             * 
             * @param value The result to add.
             * @return This builder for chaining.
             */
            public Builder addResult(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureResultIsMutable();
                result_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string result = 1;</code>
             * 
             * @param values The result to add.
             * @return This builder for chaining.
             */
            public Builder addAllResult(
                    java.lang.Iterable<java.lang.String> values) {
                ensureResultIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, result_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string result = 1;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearResult() {
                result_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string result = 1;</code>
             * 
             * @param value The bytes of the result to add.
             * @return This builder for chaining.
             */
            public Builder addResultBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureResultIsMutable();
                result_.add(value);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:responseMessage.Response)
        }

        // @@protoc_insertion_point(class_scope:responseMessage.Response)
        private static final responseMessage.ResponseOuterClass.Response DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new responseMessage.ResponseOuterClass.Response();
        }

        public static responseMessage.ResponseOuterClass.Response getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Response> PARSER = new com.google.protobuf.AbstractParser<Response>() {
            @java.lang.Override
            public Response parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Response> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Response> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public responseMessage.ResponseOuterClass.Response getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_responseMessage_Response_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_responseMessage_Response_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016response.proto\022\017responseMessage\"\032\n\010Res" +
                        "ponse\022\016\n\006result\030\001 \003(\tB\023Z\021./responseMessa" +
                        "geb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_responseMessage_Response_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_responseMessage_Response_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_responseMessage_Response_descriptor,
                new java.lang.String[] { "Result", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}