-- Creates a Table.

-- Drop the table if it exists;
DROP TABLE IF EXISTS usertable;

-- Create the user table with 5 fields.
CREATE TABLE usertable(YCSB_KEY VARCHAR PRIMARY KEY,
  FIELD1 VARCHAR, FIELD2 VARCHAR,
  FIELD3 VARCHAR, FIELD4 VARCHAR,
  FIELD5 VARCHAR, FIELD6 VARCHAR,
  FIELD7 VARCHAR, FIELD8 VARCHAR,
  FIELD9 VARCHAR, FIELD10 VARCHAR);
