name: YCSB build with Maven Wrapper

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # 3.11.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build with Maven Wrapper
      run: ./mvnw clean install site